name: Selenium InvoiceCount Tests
env:
  LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
  MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
  MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
  PG_DB_USERNAME: ${{ secrets.PG_DB_USERNAME }}
  PG_DB_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
  TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Remove existing ChromeDriver (ignore if missing)
        run: sudo rm -f /usr/local/bin/chromedriver

      - name: Install matching ChromeDriver version
        run: |
          echo "Fetching Chrome version..."
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          echo "Detected Chrome major version: $CHROME_VERSION"

          if [ -z "$CHROME_VERSION" ]; then
            echo "❌ Failed to detect Chrome version."
            exit 1
          fi

          echo "Fetching matching ChromeDriver version..."
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")

          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "❌ Failed to fetch matching ChromeDriver version for Chrome $CHROME_VERSION."
            exit 1
          fi

          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"

          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          echo "✅ ChromeDriver $CHROMEDRIVER_VERSION installed successfully"

      - name: Set timezone to Asia/Kolkata
        run: sudo timedatectl set-timezone Asia/Kolkata

      - name: Run partner_portal_invoice_count
        run: python partner_portal_invoice_count.py

      - name: Run reportcount
        run: python reportcount.py

      - name: Run send
        run: python send.py
