name: Selenium InvoiceCount Tests

env:
  LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
  MONGO_DB_USERNAME: ${{ secrets.MONGO_DB_USERNAME }}
  MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
  PG_DB_USERNAME: ${{ secrets.PG_DB_USERNAME }}
  PG_DB_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
  TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

on:
  schedule:
    - cron: '30 23 * * *'  # 5:00 AM IST
    - cron: '30 8 * * *'   # 1:00 PM IST
  workflow_dispatch:
    inputs:
      run_set:
        description: 'Which workspace set to run? (morning or afternoon)'
        required: false
        default: 'morning'

jobs:
  invoice-report-count:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Remove existing ChromeDriver (ignore if missing)
        run: sudo rm -f /usr/local/bin/chromedriver

      - name: Install matching ChromeDriver version
        run: |
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/138.0.7204.92/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set timezone to Asia/Kolkata
        run: sudo timedatectl set-timezone Asia/Kolkata

      - name: Determine RUN_SET
        id: setrunset
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RUN_SET=${{ github.event.inputs.run_set }}" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" = "30 23 * * *" ]; then
            echo "RUN_SET=morning" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" = "30 8 * * *" ]; then
            echo "RUN_SET=afternoon" >> $GITHUB_ENV
          else
            echo "RUN_SET=morning" >> $GITHUB_ENV
          fi

      - name: Run partner_portal_invoice_count.py
        run: python partner_portal_invoice_count.py

      - name: Run reportcount.py
        run: python reportcount.py

      - name: Run send.py
        run: python send.py